import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { mobileApi } from '@/api'
import { Page, Header, Loading, ErrorState } from '@/ui'
import { themes } from '@/theme'

export default function Challenges() { const client = useQueryClient(); const query = useQuery({ queryKey: ['mobile-challenges'], queryFn: mobileApi.challenges, retry: 2 }); if (query.isPending) return <Page><Loading /></Page>; if (query.isError) return <Page><ErrorState message={query.error.message} onRetry={() => void query.refetch()} /></Page>; return <ScrollView contentContainerStyle={styles.page}><Header eyebrow="A LITTLE SPARK" title="This week’s challenges." copy={`${query.data.completed_count} of ${query.data.total_count} complete · ${query.data.xp_earned} XP earned`} />{query.data.challenges.map((challenge) => <View key={challenge.id} style={styles.card}><Text style={styles.category}>{challenge.category} · {challenge.xp} XP</Text><Text style={styles.title}>{challenge.title}</Text><Text style={styles.copy}>{challenge.description}</Text>{challenge.completed ? <Text style={styles.complete}>✓ Completed</Text> : <Pressable onPress={async () => { await mobileApi.completeChallenge(challenge.id); await client.invalidateQueries({ queryKey: ['mobile-challenges'] }) }} style={styles.button}><Text style={styles.buttonText}>Mark complete</Text></Pressable>}</View>)}</ScrollView> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flexGrow: 1, padding: 24, paddingTop: 62 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginTop: 16, padding: 19 }, category: { color: themes.sage.primary, fontSize: 12, fontWeight: '800', letterSpacing: 1 }, title: { color: themes.sage.text, fontSize: 20, fontWeight: '800', marginTop: 10 }, copy: { color: themes.sage.muted, fontSize: 14, lineHeight: 21, marginTop: 6 }, button: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 12, justifyContent: 'center', marginTop: 15, minHeight: 42 }, buttonText: { color: '#fffdf8', fontWeight: '800' }, complete: { color: themes.sage.primary, fontSize: 14, fontWeight: '800', marginTop: 15 } })
