import { Link } from 'expo-router'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { mobileApi } from '@/api'
import { Page, Header, styles as ui } from '@/ui'
import { themes } from '@/theme'

const moods = ['Calm', 'Low', 'Hopeful', 'Tired', 'Overwhelmed']
const scales = [1, 2, 3, 4, 5]

export default function CheckIn() {
  const [mood, setMood] = useState(''); const [energy, setEnergy] = useState(3); const [stress, setStress] = useState(3); const [gratitude, setGratitude] = useState(''); const [thoughts, setThoughts] = useState(''); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('')
  const dashboard = useQuery({ queryKey: ['mobile-dashboard'], queryFn: mobileApi.dashboard, retry: 2 })
  const dailyQuestion = dashboard.data?.daily_checkin_question ?? 'What is on your mind today?'
  const submit = async () => { setBusy(true); setError(''); try { await mobileApi.createCheckIn({ mood, needs: [], energy, stress, thoughts: thoughts || null, gratitude: gratitude || null, completed: true }); setDone(true) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save your check-in') } finally { setBusy(false) } }
  if (done) return <Page><Header eyebrow="CHECK-IN COMPLETE" title="Thank you for checking in." copy="You made a little room for yourself today. That counts." /><View style={styles.done}><Text style={styles.doneIcon}>✦</Text><Text style={styles.doneText}>Your reflection is safely saved.</Text></View><Link href="/(tabs)" style={styles.link}>Return home</Link></Page>
  return <ScrollView contentContainerStyle={styles.page}><Header eyebrow="DAILY CHECK-IN" title="Notice what you need." copy="There is no right answer. Just meet yourself honestly." /><Text style={styles.question}>How are you feeling?</Text><View style={styles.chips}>{moods.map((item) => <Pressable key={item} onPress={() => setMood(item)} style={[styles.chip, mood === item && styles.chipActive]}><Text style={[styles.chipText, mood === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><Scale label="Energy" value={energy} onChange={setEnergy} /><Scale label="Stress" value={stress} onChange={setStress} /><Text style={styles.question}>What are you grateful for?</Text><TextInput value={gratitude} onChangeText={setGratitude} multiline style={styles.textarea} placeholder="A person, a moment, or something small…" placeholderTextColor={themes.sage.muted} /><Text style={styles.question}>{dailyQuestion}</Text><TextInput value={thoughts} onChangeText={setThoughts} multiline style={styles.textarea} placeholder="Write freely…" placeholderTextColor={themes.sage.muted} />{error ? <Text style={ui.error}>{error}</Text> : null}<Pressable disabled={!mood || busy} onPress={submit} style={[styles.submit, (!mood || busy) && styles.disabled]}>{busy ? <ActivityIndicator color="#fffdf8" /> : <Text style={styles.submitText}>Complete check-in</Text>}</Pressable></ScrollView>
}

function Scale({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <View><Text style={styles.question}>{label}</Text><View style={styles.scale}>{scales.map((item) => <Pressable key={item} onPress={() => onChange(item)} style={[styles.scaleItem, item === value && styles.scaleActive]}><Text style={[styles.scaleText, item === value && styles.scaleTextActive]}>{item}</Text></Pressable>)}</View></View> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flexGrow: 1, padding: 24, paddingTop: 62 }, question: { color: themes.sage.text, fontSize: 17, fontWeight: '800', marginTop: 27, marginBottom: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 99, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 10 }, chipActive: { backgroundColor: themes.sage.primary, borderColor: themes.sage.primary }, chipText: { color: themes.sage.text, fontSize: 14 }, chipTextActive: { color: '#fffdf8', fontWeight: '700' }, scale: { flexDirection: 'row', gap: 10 }, scaleItem: { alignItems: 'center', backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 14, borderWidth: 1, flex: 1, height: 45, justifyContent: 'center' }, scaleActive: { backgroundColor: themes.sage.accent, borderColor: themes.sage.accent }, scaleText: { color: themes.sage.text, fontWeight: '700' }, scaleTextActive: { color: '#fffdf8' }, textarea: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 15, borderWidth: 1, color: themes.sage.text, fontSize: 15, minHeight: 84, padding: 14, textAlignVertical: 'top' }, submit: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 15, justifyContent: 'center', marginTop: 26, minHeight: 52 }, submitText: { color: '#fffdf8', fontSize: 15, fontWeight: '800' }, disabled: { opacity: 0.5 }, done: { alignItems: 'center', backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 22, borderWidth: 1, marginTop: 30, padding: 26 }, doneIcon: { color: themes.sage.accent, fontSize: 35 }, doneText: { color: themes.sage.text, fontSize: 17, fontWeight: '700', marginTop: 12 }, link: { alignSelf: 'flex-start', backgroundColor: themes.sage.primary, borderRadius: 14, color: '#fffdf8', fontSize: 15, fontWeight: '800', marginTop: 22, overflow: 'hidden', paddingHorizontal: 17, paddingVertical: 13 } })
