import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { ScrollView, StyleSheet, Text, Pressable, View } from 'react-native'
import { mobileApi } from '@/api'
import { Page, Header, Loading, ErrorState } from '@/ui'
import { themes } from '@/theme'

const periods = [['day', 'Today'], ['week', 'Week'], ['month', 'Month'], ['all', 'All time']] as const
export default function Leaderboard() { const [period, setPeriod] = useState<(typeof periods)[number][0]>('week'); const query = useQuery({ queryKey: ['mobile-leaderboard', period], queryFn: () => mobileApi.leaderboard(period), refetchOnMount: 'always' }); if (query.isPending) return <Page><Loading /></Page>; if (query.isError) return <Page><ErrorState message={query.error.message} onRetry={() => void query.refetch()} /></Page>; return <ScrollView contentContainerStyle={styles.page}><Header eyebrow="COMMUNITY ENERGY" title="A little friendly encouragement." copy="See the XP everyone has earned." /><View style={styles.filters}>{periods.map(([value, label]) => <Pressable key={value} onPress={() => setPeriod(value)} style={[styles.filter, period === value && styles.active]}><Text style={[styles.filterText, period === value && styles.activeText]}>{label}</Text></Pressable>)}</View>{query.data.map((entry) => <View key={entry.user.id} style={styles.row}><Text style={styles.rank}>{entry.rank}</Text><View style={styles.avatar}><Text style={styles.avatarText}>{entry.user.name.slice(0, 1).toUpperCase()}</Text></View><Text style={styles.name}>{entry.user.name}</Text><Text style={styles.xp}>{entry.user.xp} XP</Text></View>)}</ScrollView> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flexGrow: 1, padding: 24, paddingTop: 62 }, filters: { flexDirection: 'row', gap: 7, marginTop: 23 }, filter: { borderColor: themes.sage.border, borderRadius: 99, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 9 }, active: { backgroundColor: themes.sage.primary, borderColor: themes.sage.primary }, filterText: { color: themes.sage.muted, fontSize: 12, fontWeight: '700' }, activeText: { color: '#fffdf8' }, row: { alignItems: 'center', backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 17, borderWidth: 1, flexDirection: 'row', marginTop: 12, minHeight: 62, paddingHorizontal: 14 }, rank: { color: themes.sage.primary, fontSize: 16, fontWeight: '800', width: 25 }, avatar: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 99, height: 34, justifyContent: 'center', width: 34 }, avatarText: { color: '#fffdf8', fontWeight: '800' }, name: { color: themes.sage.text, flex: 1, fontSize: 14, fontWeight: '700', marginLeft: 10 }, xp: { color: themes.sage.primary, fontSize: 13, fontWeight: '800' } })
