import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { mobileApi } from '@/api'
import { ErrorState, Header, Page } from '@/ui'
import { themes } from '@/theme'

export default function Quotes() {
  const client = useQueryClient(); const quotes = useQuery({ queryKey: ['mobile-quotes'], queryFn: () => mobileApi.quotes() }); const [text, setText] = useState(''); const [author, setAuthor] = useState(''); const [sent, setSent] = useState(false)
  if (quotes.isPending) return <Page><ActivityIndicator color={themes.sage.primary} size="large" /></Page>
  if (quotes.isError) return <Page><ErrorState message={quotes.error.message} onRetry={() => void quotes.refetch()} /></Page>
  const submit = async () => { if (!text.trim() || !author.trim()) return; await mobileApi.submitQuote({ text, author, category: 'Encouragement' }); setText(''); setAuthor(''); setSent(true) }
  return <ScrollView contentContainerStyle={styles.page}><Header eyebrow="WORDS TO KEEP" title="A little light to carry." copy="Save the words that meet you where you are, or submit one for approval." />{quotes.data.map((quote) => <View key={quote.id} style={styles.card}><Text style={styles.quote}>“{quote.text}”</Text><Text style={styles.author}>— {quote.author}</Text><Pressable onPress={async () => { await mobileApi.saveQuote(quote.id); await client.invalidateQueries({ queryKey: ['mobile-quotes'] }) }} style={styles.save}><Text style={styles.saveText}>{quote.saved ? 'Saved ✓' : 'Save quote'}</Text></Pressable></View>)}<View style={styles.form}><Text style={styles.formTitle}>Share a quote</Text><TextInput value={text} onChangeText={setText} multiline placeholder="Write something kind…" placeholderTextColor={themes.sage.muted} style={[styles.input, styles.multiline]} /><TextInput value={author} onChangeText={setAuthor} placeholder="Author" placeholderTextColor={themes.sage.muted} style={styles.input} /><Pressable disabled={!text.trim() || !author.trim()} onPress={() => void submit()} style={[styles.button, (!text.trim() || !author.trim()) && styles.disabled]}><Text style={styles.buttonText}>Submit for review</Text></Pressable>{sent ? <Text style={styles.success}>Sent for approval. Thank you for adding something good.</Text> : null}</View></ScrollView>
}

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flexGrow: 1, padding: 24, paddingTop: 62 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginTop: 16, padding: 20 }, quote: { color: themes.sage.text, fontSize: 19, lineHeight: 28 }, author: { color: themes.sage.muted, fontSize: 14, marginTop: 10 }, save: { alignSelf: 'flex-start', borderColor: themes.sage.border, borderRadius: 10, borderWidth: 1, marginTop: 16, paddingHorizontal: 13, paddingVertical: 9 }, saveText: { color: themes.sage.primary, fontWeight: '800' }, form: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginTop: 24, padding: 20 }, formTitle: { color: themes.sage.text, fontSize: 20, fontWeight: '800', marginBottom: 8 }, input: { backgroundColor: themes.sage.background, borderColor: themes.sage.border, borderRadius: 12, borderWidth: 1, color: themes.sage.text, fontSize: 16, marginTop: 12, paddingHorizontal: 14, paddingVertical: 12 }, multiline: { minHeight: 100, textAlignVertical: 'top' }, button: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 12, justifyContent: 'center', marginTop: 16, minHeight: 48 }, buttonText: { color: '#fffdf8', fontWeight: '800' }, disabled: { opacity: 0.45 }, success: { color: themes.sage.primary, lineHeight: 20, marginTop: 12 } })
