import { useQuery, useQueryClient } from '@tanstack/react-query'
import { router, useLocalSearchParams } from 'expo-router'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { mobileApi } from '@/api'
import { Page, Header, ErrorState } from '@/ui'
import { themes } from '@/theme'

export default function MobileRoom() { const { roomId } = useLocalSearchParams<{ roomId: string }>(); const id = Number(roomId); const client = useQueryClient(); const room = useQuery({ queryKey: ['mobile-room', id], queryFn: () => mobileApi.room(id), enabled: Number.isFinite(id), refetchInterval: 3000 }); const participants = useQuery({ queryKey: ['mobile-room-participants', id], queryFn: () => mobileApi.roomParticipants(id), enabled: Number.isFinite(id), refetchInterval: 3000 }); if (room.isPending || participants.isPending) return <Page><ActivityIndicator size="large" color={themes.sage.primary} /></Page>; if (room.isError || participants.isError) return <Page><ErrorState message={(room.error ?? participants.error)?.message ?? 'Unable to load room'} onRetry={() => { void room.refetch(); void participants.refetch() }} /></Page>; const join = async () => { await mobileApi.joinRoom(id); await client.invalidateQueries({ queryKey: ['mobile-room'] }); await client.invalidateQueries({ queryKey: ['mobile-room-participants'] }) }; const ready = async () => { await mobileApi.setRoomReady(id); await client.invalidateQueries({ queryKey: ['mobile-room'] }); await client.invalidateQueries({ queryKey: ['mobile-room-participants'] }) }; const start = async () => { const session = await mobileApi.createSession(id, true); router.replace(`/games/session/${session.match_id}`) }; return <ScrollView contentContainerStyle={styles.page}><Header eyebrow="GAME ROOM" title={room.data.name} copy={`${room.data.game_name} · ${room.data.participant_count}/${room.data.max_players} players`} /><View style={styles.card}>{participants.data.map((player) => <View key={player.user_id} style={styles.player}><View style={styles.dot} /><Text style={styles.playerName}>{player.display_name}</Text><Text style={styles.ready}>{player.ready ? 'Ready' : 'Waiting'}</Text></View>)}</View><Pressable onPress={() => void join()} style={styles.button}><Text style={styles.buttonText}>Join room</Text></Pressable><Pressable onPress={() => void ready()} style={styles.secondary}><Text style={styles.secondaryText}>I’m ready</Text></Pressable><Pressable onPress={() => void start()} style={styles.button}><Text style={styles.buttonText}>Start with bots</Text></Pressable></ScrollView> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flexGrow: 1, padding: 24, paddingTop: 62 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginTop: 24, padding: 18 }, player: { alignItems: 'center', borderBottomColor: themes.sage.border, borderBottomWidth: 1, flexDirection: 'row', minHeight: 50 }, dot: { backgroundColor: themes.sage.primary, borderRadius: 99, height: 10, width: 10 }, playerName: { color: themes.sage.text, flex: 1, fontSize: 15, fontWeight: '700', marginLeft: 10 }, ready: { color: themes.sage.muted, fontSize: 13 }, button: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 14, justifyContent: 'center', marginTop: 16, minHeight: 50 }, buttonText: { color: '#fffdf8', fontSize: 15, fontWeight: '800' }, secondary: { alignItems: 'center', borderColor: themes.sage.border, borderRadius: 14, borderWidth: 1, justifyContent: 'center', marginTop: 12, minHeight: 50 }, secondaryText: { color: themes.sage.text, fontSize: 15, fontWeight: '800' } })
