import { Link } from 'expo-router'
import * as ImagePicker from 'expo-image-picker'
import { useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import { useAuth } from '@/auth'
import { themes } from '@/theme'
import { themeNames } from '@/theme'
import { useTheme } from '@/theme-context'

export default function Profile() { const { user, signOut } = useAuth(); const { name: themeName, colors, setTheme } = useTheme(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const chooseAvatar = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setMessage('Allow photo access to choose a profile picture.'); return }; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.82, allowsEditing: true, aspect: [1, 1] }); if (result.canceled) return; setBusy(true); try { await import('@/api').then(({ mobileApi }) => mobileApi.updateAvatar(result.assets[0].uri)); setMessage('Profile picture updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'The picture could not be updated.'); } finally { setBusy(false) } }; return <View style={[styles.page, { backgroundColor: colors.background }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>YOUR SAFE SPACE</Text><Text style={[styles.title, { color: colors.text }]}>{user?.name}</Text><Text style={[styles.email, { color: colors.muted }]}>{user?.email}</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.level, { color: colors.primary }]}>LEVEL {user?.level ?? 1}</Text><Text style={[styles.xp, { color: colors.text }]}>{user?.xp ?? 0} XP</Text><Text style={[styles.copy, { color: colors.muted }]}>Keep showing up for yourself. Every check-in counts.</Text><Pressable disabled={busy} onPress={() => void chooseAvatar()} style={[styles.avatarButton, { borderColor: colors.border }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{busy ? 'Uploading…' : 'Change profile picture'}</Text></Pressable>{message ? <Text style={[styles.message, { color: colors.muted }]}>{message}</Text> : null}<Text style={[styles.themeLabel, { color: colors.text }]}>Choose your theme</Text><View style={styles.themeRow}>{themeNames.map((option) => <Pressable key={option} onPress={() => void setTheme(option)} style={[styles.themeChip, { backgroundColor: themes[option].surface, borderColor: option === themeName ? colors.primary : colors.border }]}><Text style={{ color: themes[option].text, fontWeight: '800' }}>{option === 'purple' ? "Tatty's garden" : option === 'crimson' ? 'Crimson Ty' : option === 'night' ? 'Night garden' : 'Sage'}</Text></Pressable>)}</View></View><View style={styles.links}><Link href="/challenges" style={[styles.link, { color: colors.primary }]}>Weekly challenges →</Link><Link href="/leaderboard" style={[styles.link, { color: colors.primary }]}>View leaderboard →</Link><Link href="/quotes" style={[styles.link, { color: colors.primary }]}>Saved quotes →</Link></View><Pressable onPress={() => void signOut()} style={[styles.logout, { borderColor: colors.border }]}><Text style={[styles.logoutText, { color: colors.text }]}>Log out</Text></Pressable></View> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flex: 1, padding: 24, paddingTop: 62 }, eyebrow: { color: themes.sage.primary, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: themes.sage.text, fontSize: 36, fontWeight: '800', marginTop: 13 }, email: { color: themes.sage.muted, fontSize: 15, marginTop: 5 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 22, borderWidth: 1, marginTop: 28, padding: 22 }, level: { color: themes.sage.primary, fontSize: 13, fontWeight: '800', letterSpacing: 1 }, xp: { color: themes.sage.text, fontSize: 29, fontWeight: '800', marginTop: 12 }, copy: { color: themes.sage.muted, fontSize: 15, lineHeight: 22, marginTop: 8 }, avatarButton: { alignItems: 'center', borderColor: themes.sage.border, borderRadius: 12, borderWidth: 1, marginTop: 18, minHeight: 44, justifyContent: 'center' }, avatarText: { color: themes.sage.primary, fontWeight: '800' }, message: { color: themes.sage.muted, fontSize: 13, marginTop: 10 }, themeLabel: { fontSize: 14, fontWeight: '800', marginTop: 22 }, themeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 }, themeChip: { borderRadius: 10, borderWidth: 2, paddingHorizontal: 10, paddingVertical: 9 }, links: { gap: 12, marginTop: 18 }, link: { color: themes.sage.primary, fontSize: 15, fontWeight: '800' }, logout: { alignItems: 'center', borderColor: themes.sage.border, borderRadius: 14, borderWidth: 1, marginTop: 22, minHeight: 50, justifyContent: 'center' }, logoutText: { color: themes.sage.text, fontSize: 15, fontWeight: '800' } })
