import { Link } from 'expo-router'
import * as ImagePicker from 'expo-image-picker'
import { useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import { useAuth } from '@/auth'
import { themes } from '@/theme'

export default function Profile() { const { user, signOut } = useAuth(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const chooseAvatar = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setMessage('Allow photo access to choose a profile picture.'); return }; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.82, allowsEditing: true, aspect: [1, 1] }); if (result.canceled) return; setBusy(true); try { await import('@/api').then(({ mobileApi }) => mobileApi.updateAvatar(result.assets[0].uri)); setMessage('Profile picture updated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'The picture could not be updated.'); } finally { setBusy(false) } }; return <View style={styles.page}><Text style={styles.eyebrow}>YOUR SAFE SPACE</Text><Text style={styles.title}>{user?.name}</Text><Text style={styles.email}>{user?.email}</Text><View style={styles.card}><Text style={styles.level}>LEVEL {user?.level ?? 1}</Text><Text style={styles.xp}>{user?.xp ?? 0} XP</Text><Text style={styles.copy}>Keep showing up for yourself. Every check-in counts.</Text><Pressable disabled={busy} onPress={() => void chooseAvatar()} style={styles.avatarButton}><Text style={styles.avatarText}>{busy ? 'Uploading…' : 'Change profile picture'}</Text></Pressable>{message ? <Text style={styles.message}>{message}</Text> : null}</View><View style={styles.links}><Link href="/challenges" style={styles.link}>Weekly challenges →</Link><Link href="/leaderboard" style={styles.link}>View leaderboard →</Link><Link href="/quotes" style={styles.link}>Saved quotes →</Link></View><Pressable onPress={() => void signOut()} style={styles.logout}><Text style={styles.logoutText}>Log out</Text></Pressable></View> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, flex: 1, padding: 24, paddingTop: 62 }, eyebrow: { color: themes.sage.primary, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, title: { color: themes.sage.text, fontSize: 36, fontWeight: '800', marginTop: 13 }, email: { color: themes.sage.muted, fontSize: 15, marginTop: 5 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 22, borderWidth: 1, marginTop: 28, padding: 22 }, level: { color: themes.sage.primary, fontSize: 13, fontWeight: '800', letterSpacing: 1 }, xp: { color: themes.sage.text, fontSize: 29, fontWeight: '800', marginTop: 12 }, copy: { color: themes.sage.muted, fontSize: 15, lineHeight: 22, marginTop: 8 }, avatarButton: { alignItems: 'center', borderColor: themes.sage.border, borderRadius: 12, borderWidth: 1, marginTop: 18, minHeight: 44, justifyContent: 'center' }, avatarText: { color: themes.sage.primary, fontWeight: '800' }, message: { color: themes.sage.muted, fontSize: 13, marginTop: 10 }, links: { gap: 12, marginTop: 18 }, link: { color: themes.sage.primary, fontSize: 15, fontWeight: '800' }, logout: { alignItems: 'center', borderColor: themes.sage.border, borderRadius: 14, borderWidth: 1, marginTop: 22, minHeight: 50, justifyContent: 'center' }, logoutText: { color: themes.sage.text, fontSize: 15, fontWeight: '800' } })
