import { useQuery, useQueryClient } from '@tanstack/react-query'
import * as ImagePicker from 'expo-image-picker'
import { useState } from 'react'
import { ActivityIndicator, FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { assetUrl, mobileApi, type Post } from '@/api'
import { Page, Header, ErrorState } from '@/ui'
import { themes } from '@/theme'

export default function Community() {
  const client = useQueryClient(); const posts = useQuery({ queryKey: ['mobile-posts'], queryFn: () => mobileApi.posts(), retry: 2 }); const [text, setText] = useState(''); const [imageUri, setImageUri] = useState<string | null>(null); const [posting, setPosting] = useState(false); const [error, setError] = useState('')
  const chooseImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Allow photo access to attach an image.'); return }; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 }); if (!result.canceled) setImageUri(result.assets[0].uri) }
  const create = async () => { if (!text.trim()) return; setPosting(true); setError(''); try { if (imageUri) await mobileApi.createPostWithImage(text, imageUri); else await mobileApi.createPost(text); setText(''); setImageUri(null); await client.invalidateQueries({ queryKey: ['mobile-posts'] }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to share your post') } finally { setPosting(false) } }
  if (posts.isPending) return <Page><Text style={styles.loading}>Loading your community…</Text></Page>
  if (posts.isError) return <Page><ErrorState message={posts.error.message} onRetry={() => void posts.refetch()} /></Page>
  return <FlatList data={posts.data} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.page} ListHeaderComponent={<><Header eyebrow="YOUR COMMUNITY" title="A softer place to land." copy="Share encouragement, reflections, and small wins." /><View style={styles.composer}><TextInput value={text} onChangeText={setText} multiline style={styles.input} placeholder="What would you like to share?" placeholderTextColor={themes.sage.muted} />{imageUri ? <View style={styles.preview}><Image source={{ uri: imageUri }} style={styles.previewImage} /><Pressable onPress={() => setImageUri(null)}><Text style={styles.remove}>Remove</Text></Pressable></View> : null}<View style={styles.composerActions}><Pressable onPress={() => void chooseImage()} style={styles.attach}><Text style={styles.attachText}>Add photo</Text></Pressable><Pressable disabled={posting || !text.trim()} onPress={create} style={[styles.postButton, (!text.trim() || posting) && styles.disabled]}>{posting ? <ActivityIndicator color="#fffdf8" /> : <Text style={styles.postText}>Post · +5 XP</Text>}</Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View></>} renderItem={({ item }) => <PostCard post={item} onUpdate={() => void client.invalidateQueries({ queryKey: ['mobile-posts'] })} />} />
}

function PostCard({ post, onUpdate }: { post: Post; onUpdate: () => void }) { const [reply, setReply] = useState(''); const [showReply, setShowReply] = useState(false); const react = async (kind: 'like' | 'dislike') => { await mobileApi.react(post.id, kind); onUpdate() }; const sendReply = async () => { if (!reply.trim()) return; await mobileApi.reply(post.id, reply); setReply(''); onUpdate() }; return <View style={styles.card}><View style={styles.author}><View style={styles.avatar}><Text style={styles.avatarText}>{post.author_name.slice(0, 1).toUpperCase()}</Text></View><View><Text style={styles.authorName}>{post.author_name}</Text><Text style={styles.date}>{new Date(post.created_at).toLocaleDateString()}</Text></View></View><Text style={styles.postBody}>{post.text}</Text>{post.image_url ? <Image source={{ uri: assetUrl(post.image_url) ?? undefined }} style={styles.postImage} resizeMode="cover" /> : null}<View style={styles.actions}><Pressable onPress={() => void react('like')}><Text style={styles.action}>♡ {post.like_count}</Text></Pressable><Pressable onPress={() => void react('dislike')}><Text style={styles.action}>▽ {post.dislike_count}</Text></Pressable><Pressable onPress={() => setShowReply((value) => !value)}><Text style={styles.action}>Reply {post.comment_count ? `· ${post.comment_count}` : ''}</Text></Pressable></View>{showReply ? <View style={styles.reply}><TextInput value={reply} onChangeText={setReply} style={styles.replyInput} placeholder="Write a kind reply…" placeholderTextColor={themes.sage.muted} /><Pressable onPress={() => void sendReply()}><Text style={styles.replyButton}>Send</Text></Pressable></View> : null}</View> }

const styles = StyleSheet.create({ page: { backgroundColor: themes.sage.background, padding: 24, paddingTop: 62 }, loading: { color: themes.sage.muted, paddingTop: 60, textAlign: 'center' }, composer: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginBottom: 18, marginTop: 24, padding: 15 }, input: { color: themes.sage.text, fontSize: 15, minHeight: 70, textAlignVertical: 'top' }, composerActions: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, attach: { borderColor: themes.sage.border, borderRadius: 10, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 }, attachText: { color: themes.sage.primary, fontWeight: '800' }, preview: { alignItems: 'center', flexDirection: 'row', gap: 10, marginTop: 10 }, previewImage: { borderRadius: 10, height: 64, width: 64 }, remove: { color: '#b24747', fontWeight: '700' }, postButton: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 12, justifyContent: 'center', minHeight: 42, paddingHorizontal: 15 }, postText: { color: '#fffdf8', fontSize: 13, fontWeight: '800' }, disabled: { opacity: 0.5 }, error: { color: '#b24747', fontSize: 13, marginTop: 10 }, card: { backgroundColor: themes.sage.surface, borderColor: themes.sage.border, borderRadius: 20, borderWidth: 1, marginBottom: 14, padding: 17 }, author: { alignItems: 'center', flexDirection: 'row' }, avatar: { alignItems: 'center', backgroundColor: themes.sage.primary, borderRadius: 99, height: 38, justifyContent: 'center', width: 38 }, avatarText: { color: '#fffdf8', fontWeight: '800' }, authorName: { color: themes.sage.text, fontSize: 14, fontWeight: '800', marginLeft: 10 }, date: { color: themes.sage.muted, fontSize: 11, marginLeft: 10, marginTop: 2 }, postBody: { color: themes.sage.text, fontSize: 16, lineHeight: 24, marginTop: 16 }, postImage: { borderRadius: 14, height: 220, marginTop: 14, width: '100%' }, actions: { borderTopColor: themes.sage.border, borderTopWidth: 1, flexDirection: 'row', gap: 18, marginTop: 16, paddingTop: 13 }, action: { color: themes.sage.primary, fontSize: 13, fontWeight: '700' }, reply: { alignItems: 'center', borderTopColor: themes.sage.border, borderTopWidth: 1, flexDirection: 'row', gap: 8, marginTop: 14, paddingTop: 12 }, replyInput: { backgroundColor: themes.sage.background, borderRadius: 10, color: themes.sage.text, flex: 1, minHeight: 40, paddingHorizontal: 10 }, replyButton: { color: themes.sage.primary, fontWeight: '800' } })
