/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesSessionMatchIdRouteImport } from './routes/games.session.$matchId'
import { Route as GamesPlayMatchIdRouteImport } from './routes/games.play.$matchId'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSessionMatchIdRoute = GamesSessionMatchIdRouteImport.update({
  id: '/session/$matchId',
  path: '/session/$matchId',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPlayMatchIdRoute = GamesPlayMatchIdRouteImport.update({
  id: '/play/$matchId',
  path: '/play/$matchId',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/community'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games/play/$matchId'
    | '/games/session/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/community'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games/play/$matchId'
    | '/games/session/$matchId'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/community'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games/play/$matchId'
    | '/games/session/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  CommunityRoute: typeof CommunityRoute
  GamesRoute: typeof GamesRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuotesRoute: typeof QuotesRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/session/$matchId': {
      id: '/games/session/$matchId'
      path: '/session/$matchId'
      fullPath: '/games/session/$matchId'
      preLoaderRoute: typeof GamesSessionMatchIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/play/$matchId': {
      id: '/games/play/$matchId'
      path: '/play/$matchId'
      fullPath: '/games/play/$matchId'
      preLoaderRoute: typeof GamesPlayMatchIdRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesPlayMatchIdRoute: typeof GamesPlayMatchIdRoute
  GamesSessionMatchIdRoute: typeof GamesSessionMatchIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesPlayMatchIdRoute: GamesPlayMatchIdRoute,
  GamesSessionMatchIdRoute: GamesSessionMatchIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  CommunityRoute: CommunityRoute,
  GamesRoute: GamesRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuotesRoute: QuotesRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
