/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesSessionMatchIdRouteImport } from './routes/games.session.$matchId'
import { Route as GamesRoomsRoomIdRouteImport } from './routes/games.rooms.$roomId'
import { Route as GamesPlayMatchIdRouteImport } from './routes/games.play.$matchId'
import { Route as GamesRoomsInviteTokenRouteImport } from './routes/games.rooms.invite.$token'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSessionMatchIdRoute = GamesSessionMatchIdRouteImport.update({
  id: '/session/$matchId',
  path: '/session/$matchId',
  getParentRoute: () => GamesRoute,
} as any)
const GamesRoomsRoomIdRoute = GamesRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => GamesRoute,
} as any)
const GamesPlayMatchIdRoute = GamesPlayMatchIdRouteImport.update({
  id: '/play/$matchId',
  path: '/play/$matchId',
  getParentRoute: () => GamesRoute,
} as any)
const GamesRoomsInviteTokenRoute = GamesRoomsInviteTokenRouteImport.update({
  id: '/rooms/invite/$token',
  path: '/rooms/invite/$token',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games/': typeof GamesIndexRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/rooms/$roomId': typeof GamesRoomsRoomIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
  '/games/rooms/invite/$token': typeof GamesRoomsInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games': typeof GamesIndexRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/rooms/$roomId': typeof GamesRoomsRoomIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
  '/games/rooms/invite/$token': typeof GamesRoomsInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/challenges': typeof ChallengesRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/registration': typeof RegistrationRoute
  '/games/': typeof GamesIndexRoute
  '/games/play/$matchId': typeof GamesPlayMatchIdRoute
  '/games/rooms/$roomId': typeof GamesRoomsRoomIdRoute
  '/games/session/$matchId': typeof GamesSessionMatchIdRoute
  '/games/rooms/invite/$token': typeof GamesRoomsInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/challenges'
    | '/check-in'
    | '/community'
    | '/contact'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games/'
    | '/games/play/$matchId'
    | '/games/rooms/$roomId'
    | '/games/session/$matchId'
    | '/games/rooms/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/challenges'
    | '/check-in'
    | '/community'
    | '/contact'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games'
    | '/games/play/$matchId'
    | '/games/rooms/$roomId'
    | '/games/session/$matchId'
    | '/games/rooms/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/challenges'
    | '/check-in'
    | '/community'
    | '/contact'
    | '/games'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/registration'
    | '/games/'
    | '/games/play/$matchId'
    | '/games/rooms/$roomId'
    | '/games/session/$matchId'
    | '/games/rooms/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChallengesRoute: typeof ChallengesRoute
  CheckInRoute: typeof CheckInRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuotesRoute: typeof QuotesRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/session/$matchId': {
      id: '/games/session/$matchId'
      path: '/session/$matchId'
      fullPath: '/games/session/$matchId'
      preLoaderRoute: typeof GamesSessionMatchIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/rooms/$roomId': {
      id: '/games/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/games/rooms/$roomId'
      preLoaderRoute: typeof GamesRoomsRoomIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/play/$matchId': {
      id: '/games/play/$matchId'
      path: '/play/$matchId'
      fullPath: '/games/play/$matchId'
      preLoaderRoute: typeof GamesPlayMatchIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/rooms/invite/$token': {
      id: '/games/rooms/invite/$token'
      path: '/rooms/invite/$token'
      fullPath: '/games/rooms/invite/$token'
      preLoaderRoute: typeof GamesRoomsInviteTokenRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesIndexRoute: typeof GamesIndexRoute
  GamesPlayMatchIdRoute: typeof GamesPlayMatchIdRoute
  GamesRoomsRoomIdRoute: typeof GamesRoomsRoomIdRoute
  GamesSessionMatchIdRoute: typeof GamesSessionMatchIdRoute
  GamesRoomsInviteTokenRoute: typeof GamesRoomsInviteTokenRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIndexRoute: GamesIndexRoute,
  GamesPlayMatchIdRoute: GamesPlayMatchIdRoute,
  GamesRoomsRoomIdRoute: GamesRoomsRoomIdRoute,
  GamesSessionMatchIdRoute: GamesSessionMatchIdRoute,
  GamesRoomsInviteTokenRoute: GamesRoomsInviteTokenRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChallengesRoute: ChallengesRoute,
  CheckInRoute: CheckInRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuotesRoute: QuotesRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
